name: Build torch-cublas-hgemm Wheel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) Checkout your fork (which now contains setup.py at the root)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Install Python 3.12
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3) Install build tools (CMake, Ninja, setuptools/wheel) + PyTorch+CUDA
      - name: Install build deps & PyTorch
        run: |
          python -m pip install --upgrade pip setuptools wheel cmake ninja
          pip install torch==2.8.0+cu128 \
            --extra-index-url https://download.pytorch.org/whl/cu128

      # 4) Build the wheel in the root (where setup.py lives)
      - name: Build wheel
        run: python setup.py bdist_wheel --dist-dir dist

      # 5) Smoke-test the built wheel
      - name: Smoke-test wheel
        run: |
          pip install dist/*.whl
          python - <<'PYCODE'
          import torch
          from cublas_ops import CublasLinear
          lin = CublasLinear(4,4,device="cuda",dtype=torch.float16)
          x = torch.randn(1,4,4,device="cuda").half()
          print("✅ PASSED – output shape:", lin(x).shape)
          PYCODE

      # 6) Upload the wheel artifact for download
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: torch-cublas-hgemm-cp312-cu128
          path: dist/*.whl
