# .github/workflows/build-cublas-hgemm.yml

name: Build wheel for aredden/torch-cublas-hgemm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows-cp312-cu128:
    name: Windows-x64 Python 3.12 (CUDA 12.8, PyTorch 2.8.0+cu128)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Upgrade pip & install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build cmake ninja

      - name: Install PyTorch 2.8.0+cu128
        run: |
          pip install torch==2.8.0+cu128 --extra-index-url https://download.pytorch.org/whl/cu128

      - name: Build the CublasOps wheel
        run: |
          python -m build --wheel --outdir dist/

      - name: Quick smoke-test
        run: |
          python - <<'PYCODE'
          import torch
          from cublas_ops import CublasLinear
          lin = CublasLinear(8, 8, bias=False, device="cuda", dtype=torch.float16)
          x = torch.randn(2, 8, 8, device="cuda").half()
          y = lin(x)
          print("Output shape:", y.shape)
          PYCODE

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: torch-cublas-hgemm-cp312-cu128
          path: dist/*.whl


