name: Build torch-cublas-hgemm Windows cp312 cu128

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows-wheel:
    runs-on: windows-2022
    timeout-minutes: 120
    steps:
      - name: Checkout this workflow repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout upstream torch-cublas-hgemm into upstream
        uses: actions/checkout@v4
        with:
          repository: aredden/torch-cublas-hgemm
          path: upstream
          fetch-depth: 0

      - name: Show filesystem top-level (debug)
        run: |
          echo "=== top-level listing ==="
          dir
          echo "=== listing upstream folder ==="
          dir .\upstream

      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Ensure pip tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel ninja

      - name: Install CUDA 12.8 toolkit (silent)
        shell: pwsh
        run: |
          $url = 'https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda_12.8.0_windows_network.exe'
          $out = 'C:\windows\temp\cuda_12.8.exe'
          Invoke-WebRequest -Uri $url -OutFile $out
          Start-Process -FilePath $out -ArgumentList '-s' -Wait
          $cudaPath = 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8\bin'
          [Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';' + $cudaPath, 'Process')
          nvcc --version

      - name: Install PyTorch for CUDA 12.8
        run: |
          python -m pip install --extra-index-url https://download.pytorch.org/whl/cu128 torch --upgrade

      - name: Install build deps
        run: |
          python -m pip install --upgrade cmake

      - name: Show upstream tree before build (debug)
        run: |
          echo "=== upstream tree (first 200 lines) ==="
          powershell -Command "Get-ChildItem -Recurse -Force .\upstream | Select-Object FullName | Out-String -Width 4096" | Select-String -Pattern "."
          echo "=== show first-level files in upstream ==="
          dir .\upstream

      - name: Build wheel from upstream folder (debug verbose)
        working-directory: ./upstream
        run: |
          echo "PWD:" && powershell -Command "Get-Location"
          python -V
          python -m pip --version
          echo "Listing upstream files (recursive, first 300 lines):"
          powershell -Command "Get-ChildItem -Recurse -Force . | Select-Object FullName,Length | Out-String -Width 4096" | Select-String -Pattern "."
          echo "Running pip wheel now (verbose):"
          python -m pip wheel . --no-deps -w ../wheelhouse --verbose 2>&1 | tee pip_wheel_build.log
          echo "==== last 200 lines of pip build log ===="
          powershell -Command "Get-Content pip_wheel_build.log -Tail 200" || true

      - name: Show produced wheels
        run: |
          echo "=== wheelhouse listing ==="
          dir ..\wheelhouse
          Get-ChildItem ..\wheelhouse | Select-Object Name, Length

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse
          path: ../wheelhouse/*.whl
