name: Build torch-cublas-hgemm Windows cp312 cu128

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows-wheel:
    runs-on: windows-2022
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Ensure pip tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel ninja

      - name: Install CUDA 12.8 toolkit (silent)
        shell: pwsh
        run: |
          $url = 'https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda_12.8.0_windows_network.exe'
          $out = 'C:\windows\temp\cuda_12.8.exe'
          Invoke-WebRequest -Uri $url -OutFile $out
          Start-Process -FilePath $out -ArgumentList '-s' -Wait
          $cudaPath = 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8\bin'
          [Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';' + $cudaPath, 'Process')
          nvcc --version

      - name: Install PyTorch for CUDA 12.8
        run: |
          python -m pip install --extra-index-url https://download.pytorch.org/whl/cu128 torch --upgrade

      - name: Build deps
        run: |
          python -m pip install --upgrade cmake

      - name: Clone upstream if missing
        run: |
          if (-not (Test-Path -Path './torch-cublas-hgemm')) {
            git clone https://github.com/aredden/torch-cublas-hgemm.git
          }

      - name: Build wheel
        working-directory: ./torch-cublas-hgemm
        run: |
          python -m pip wheel . --no-deps -w ../wheelhouse --verbose

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse
          path: ../wheelhouse/*.whl
