name: Build torch-cublas-hgemm Windows cp312 cu128

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows-wheel:
    runs-on: windows-2022
    timeout-minutes: 120

    steps:
      - name: Checkout upstream repo into job root
        uses: actions/checkout@v4
        with:
          repository: aredden/torch-cublas-hgemm
          path: .
          fetch-depth: 0

      - name: Confirm repo files present (debug)
        run: |
          echo "=== CWD ==="
          powershell -Command "Get-Location"
          echo "=== top-level listing ==="
          dir
          echo "=== show setup.py ==="
          type setup.py || echo "setup.py not found"

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Ensure pip tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel ninja

      - name: Install PyTorch for CUDA 12.8
        run: |
          python -m pip install --extra-index-url https://download.pytorch.org/whl/cu128 torch --upgrade

      - name: Install build deps
        run: |
          python -m pip install --upgrade cmake

      - name: Build wheel from repo root (verbose)
        run: |
          echo "Running in:" && powershell -Command "Get-Location"
          echo "Files to build:" && powershell -Command "Get-ChildItem -Force | Select-Object Name | Out-String -Width 4096"
          python -m pip wheel . --no-deps -w ./wheelhouse --verbose

      - name: Show produced wheels
        run: |
          echo "=== wheelhouse ==="
          dir .\wheelhouse || echo "no wheelhouse"

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl
