name: Build torch-cublas-hgemm Windows cp312 cu128

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows-wheel:
    runs-on: windows-2022
    timeout-minutes: 240

    steps:
      - name: Checkout aredden/torch-cublas-hgemm into job root
        uses: actions/checkout@v4
        with:
          repository: aredden/torch-cublas-hgemm
          path: .
          fetch-depth: 0

      - name: Confirm repo files present (debug)
        run: |
          echo "=== CWD ==="
          powershell -Command "Get-Location"
          echo "=== top-level listing ==="
          dir
          echo "=== show setup.py ==="
          type setup.py || echo "setup.py not found"

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Ensure pip tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel ninja cmake

      - name: Install CUDA 12.8 via cuda-toolkit action (Windows)
        uses: Jimver/cuda-toolkit@v2
        with:
          cuda: '12.8.0'
          method: 'local'    # local installer on Windows
          windows_method: 'network' # network installer on Windows

      - name: Ensure CUDA env vars visible to process (pwsh)
        shell: pwsh
        run: |
          $cudaRoot = 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8'
          if (Test-Path $cudaRoot) {
            Write-Host "Setting CUDA_HOME and PATH for process"
            [Environment]::SetEnvironmentVariable('CUDA_HOME', $cudaRoot, 'Process')
            $bin = Join-Path $cudaRoot 'bin'
            $libx64 = Join-Path $cudaRoot 'lib\x64'
            $newPath = "$env:PATH;$bin;$libx64"
            [Environment]::SetEnvironmentVariable('PATH', $newPath, 'Process')
          } else {
            Write-Host "CUDA path not found at $cudaRoot (action may have installed elsewhere)"
          }
          nvcc --version || Write-Host "nvcc not found"

      - name: Debug CUDA environment (details)
        shell: pwsh
        run: |
          echo "CUDA_HOME=$env:CUDA_HOME"
          echo "PATH snippet:"
          echo $env:PATH | Select-String -Pattern "CUDA" -AllMatches || true
          $p = 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8'
          if (Test-Path $p) { Write-Host "Found: $p"; Get-ChildItem -Path (Join-Path $p 'include') -ErrorAction SilentlyContinue | Select-Object Name | Out-String -Width 4096; Get-ChildItem -Path (Join-Path $p 'lib\x64') -ErrorAction SilentlyContinue | Select-Object Name | Out-String -Width 4096 } else { Write-Host "Not found: $p" }

      - name: Install PyTorch for CUDA 12.8
        run: |
          python -m pip install --extra-index-url https://download.pytorch.org/whl/cu128 torch --upgrade

      - name: Show repo tree (debug)
        run: |
          echo "=== recursive tree for repo (first 300 lines) ==="
          powershell -Command "Get-ChildItem -Recurse -Force . | Select-Object FullName,Length | Out-String -Width 4096" | Select-String -Pattern "."

      - name: Build wheel from repo root (verbose)
        run: |
          echo "Running in:" && powershell -Command "Get-Location"
          echo "Files to build:" && powershell -Command "Get-ChildItem -Force | Select-Object Name | Out-String -Width 4096"
          python -m pip wheel . --no-deps -w ./wheelhouse --verbose 2>&1 | tee pip_wheel_build.log
          echo "==== last 200 lines of pip build log ===="
          powershell -Command "Get-Content pip_wheel_build.log -Tail 200" || true

      - name: Show produced wheels
        run: |
          echo "=== wheelhouse listing ==="
          dir .\wheelhouse || echo "no wheelhouse"

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl
