name: Build torch-cublas-hgemm Windows cp312 cu128

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows-wheel:
    runs-on: windows-2022
    timeout-minutes: 120

    steps:
      - name: Checkout workflow repo (no-op)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout aredden/torch-cublas-hgemm into torch-cublas-hgemm
        uses: actions/checkout@v4
        with:
          repository: aredden/torch-cublas-hgemm
          path: torch-cublas-hgemm
          fetch-depth: 0

      - name: Confirm files are present (debug)
        run: |
          echo "=== job workspace ==="
          dir
          echo "=== torch-cublas-hgemm top-level ==="
          dir .\torch-cublas-hgemm
          echo "=== show setup.py contents ==="
          type .\torch-cublas-hgemm\setup.py

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Ensure pip tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel ninja

      - name: Install PyTorch for CUDA 12.8
        run: |
          python -m pip install --extra-index-url https://download.pytorch.org/whl/cu128 torch --upgrade

      - name: Install CUDA 12.8 toolkit (silent) - attempt network installer
        shell: pwsh
        run: |
          $url = 'https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda_12.8.0_windows_network.exe'
          $out = 'C:\windows\temp\cuda_12.8.exe'
          Invoke-WebRequest -Uri $url -OutFile $out -UseBasicParsing
          Start-Process -FilePath $out -ArgumentList '-s' -Wait
          $cudaPath = 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8\bin'
          if (Test-Path $cudaPath) {
            Write-Host "CUDA installed at $cudaPath"
            [Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';' + $cudaPath, 'Process')
          } else {
            Write-Host "CUDA installer ran but expected path not found. Continuing anyway."
          }
          nvcc --version || Write-Host "nvcc not found (continue if runner provides required headers via torch wheel)."

      - name: Install build deps
        run: |
          python -m pip install --upgrade cmake

      - name: Show repo tree (debug)
        run: |
          echo "=== recursive tree for torch-cublas-hgemm (first 300 lines) ==="
          powershell -Command "Get-ChildItem -Recurse -Force .\torch-cublas-hgemm | Select-Object FullName,Length | Out-String -Width 4096" | Select-String -Pattern "."

      - name: Build wheel from torch-cublas-hgemm (verbose)
        working-directory: .\torch-cublas-hgemm
        run: |
          echo "Working directory:" && powershell -Command "Get-Location"
          python -V
          python -m pip --version
          echo "Running: python -m pip wheel . --no-deps -w ../wheelhouse --verbose"
          python -m pip wheel . --no-deps -w ../wheelhouse --verbose 2>&1 | tee pip_wheel_build.log
          echo "==== last 200 lines of pip build log ===="
          powershell -Command "Get-Content pip_wheel_build.log -Tail 200" || true

      - name: Show produced wheels
        run: |
          echo "=== wheelhouse listing ==="
          dir ..\wheelhouse || true
          powershell -Command "Get-ChildItem ..\wheelhouse | Select-Object Name, Length | Out-String -Width 4096" | Select-String -Pattern "." || true

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse
          path: ..\wheelhouse\*.whl
